language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"

script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.6" ]]; then pip install unittest2 ; fi
  - python setup.py test
  - if [[ "$TRAVIS_PYTHON_VERSION" != "nightly" ]]; then coverage run setup.py test ; fi

matrix:
  allow_failures:
    # Allow failures on 2.6 as it doesn't detect implicit parameters
    - python: "2.6"

notifications:
  email: false
before_install:
  - pip install codecov
after_success:
  - codecov
